### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by graywolf336** [Kugge/BestViewDistance#12]
Versions:
-  WorldEdit v7.0.0-beta-05;6bbf29b
- BestViewDistance v11.9
- Paper version git-Paper-588 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

```
[15:24:01] [Craft Scheduler Thread - 1/WARN]: [BestViewDistance] Plugin BestViewDistance v11.9 generated an exception while executing task 13
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.CraftWorld cannot be cast to com.sk89q.worldedit.world.World
	at me.lxct.bestviewdistance.functions.hooks.WorldGuardHook.getPlayerRegions(WorldGuardHook.java:21) ~[?:?]
	at me.lxct.bestviewdistance.functions.BVDPlayer.getCurrentMaxLimit(BVDPlayer.java:98) ~[?:?]
	at me.lxct.bestviewdistance.functions.BVDPlayer.setScheduledViewDistance(BVDPlayer.java:149) ~[?:?]
	at me.lxct.bestviewdistance.functions.util.Calculations.calculatePlayersBestViewDistance(Calculations.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-588]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-588]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_201]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**Comment by graywolf336** [comment]
Closing as a duplicate of #15 (his has better descriptions)
