### ISSUE TITLE
NullPointerException: null at start-up when loading NPCs.

### ISSUE THREAD

**Issue by mibby** [Kugge/BestViewDistance#14]
Paper dev 588 (Spigot 1.13.2)
BestViewDistance compiled as of commit https://github.com/Kugge/BestViewDistance/commit/8e335e8d61ba77dd4e1c83dfda28e23ac98771f9

This exception occurs at start-up for every NPC loaded with Citizens. Need to ignore all players with the meta 'NPC' from affecting view distance checks?

Config
https://paste.ubuntu.com/p/prQjMy2Qvk/

```
[13:48:32] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to BestViewDistance v11.9
java.lang.NullPointerException: null
	at me.lxct.bestviewdistance.event.OnTeleport.onPlayerTeleport(OnTeleport.java:25) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.13.2.jar:git-Paper-588]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:722) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:334) ~[patched_1.13.2.jar:git-Paper-588]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:233) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:143) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$3.run(Citizens.java:331) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-588]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by mibby** [comment]
As well as this exception spamming in console.

```
[13:48:32] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to BestViewDistance v11.9
java.lang.NullPointerException: null
	at me.lxct.bestviewdistance.event.OnTeleport.onPlayerTeleport(OnTeleport.java:25) ~[?:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.13.2.jar:git-Paper-588]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:722) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:334) ~[patched_1.13.2.jar:git-Paper-588]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:233) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:190) ~[?:?]
	at net.citizensnpcs.EventListen.spawn(EventListen.java:610) ~[?:?]
	at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:580) ~[?:?]
	at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:144) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor659.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-588]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-588]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.Chunk.addEntities(Chunk.java:981) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.postChunk(PaperAsyncChunkProvider.java:535) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:116) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:110) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:105) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:98) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1013) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-588]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-588]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Edit: Disabling this setting seems to fix the problem for now. ``UseTeleportView: false``
