### ISSUE TITLE
generated an exception

### ISSUE THREAD

**Issue by Sakanas** [Kugge/BestViewDistance#2]
`[20:56:40] [Server thread/INFO]: Severu[/127.0.0.1:57192] logged in with entity id 30 at ([world]118.0, 63.0, 143.0)
[20:56:46] [Craft Scheduler Thread - 50/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:56:57] [Craft Scheduler Thread - 56/INFO]: [AuthMe] Severu logged in!
[20:56:57] [Server thread/INFO]: [AuthMe] Severu registered 127.0.0.1
[20:57:00] [Craft Scheduler Thread - 52/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:57:15] [Craft Scheduler Thread - 56/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:57:30] [Craft Scheduler Thread - 52/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:57:31] [Server thread/WARN]: [CraftBook] Warning! You have no mechanics enabled, the plugin will appear to do nothing until a feature is enabled!
[20:57:45] [Craft Scheduler Thread - 52/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:58:00] [Craft Scheduler Thread - 57/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:58:16] [Craft Scheduler Thread - 52/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:58:31] [Craft Scheduler Thread - 57/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:58:46] [Craft Scheduler Thread - 58/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:59:01] [Craft Scheduler Thread - 52/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:59:16] [Craft Scheduler Thread - 59/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:59:31] [Craft Scheduler Thread - 58/WARN]: [BestViewDistance] Plugin BestViewDistance v6.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getClientViewDistance()I
	at me.lxct.bestviewdistance.functions.Get.getViewDistance(Get.java:28) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setClientSettingLimit(Set.java:29) ~[?:?]
	at me.lxct.bestviewdistance.functions.Set.setPlayersBestViewDistance(Set.java:77) ~[?:?]
	at me.lxct.bestviewdistance.BestViewDistance.lambda$new$0(BestViewDistance.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`

**Comment by Lxct** [comment]
You need to use the latest version of Paper.
This should solve the problem.
Latest build : #440
https://papermc.io/ci/job/Paper-1.13/

**Comment by Sakanas** [comment]
solved ^^

**Comment by Lxct** [comment]
Good :1st_place_medal:
