### ISSUE TITLE
Command to force re-calculate view distance for when your view distance gets stuck on 4.

### ISSUE THREAD

**Issue by mibby** [Kugge/BestViewDistance#27]
Would it be possible to add a command to force view distance to re-calculate and re-send for when it bugs out and forever gets stuck at a radius of 4?

**Comment by sofianedjerbi** [comment]
It's not normal to get stuck on a view dist. of 4. 
Please provide us more information about that.

**Comment by Germanode** [comment]
Stuck here too. Always on 4 after joining. This not only happens to players but is happening to to me as well.
![Screenshot_41](https://user-images.githubusercontent.com/17865871/61660451-22479a80-acca-11e9-8d48-0c7eb68e8eb7.png)

This is a normal 1.12.2 player on a 1.12.2 server with view distance set on 12 in client settings. Ping below 50 and server TPS full 20.00.

The last version seems to be suffering a bug (Version before this, didn't have this bug). 

The plugin detects a wrong player setting and adjusts the view distance to that wrong setting. Only after changing view distance from the client settings, the plugin picks up the real set view distance and adapts the distance.

The only thing changed in config were per-world-distances.

**Comment by Germanode** [comment]
Also, just noticed this error upon logging in:

`[19:50:46 ERROR]: [BestViewDistance] Unhandled exception occured in onPacketReceiving(PacketEvent) for BestViewDistance
java.lang.NullPointerException: null
at me.lxct.bestviewdistance.functions.hooks.ProtocolLibHook$1.onPacketReceiving(ProtocolLibHook.java:26) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:509) ~[?:?]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1617]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[patched_1.12.2.jar:git-Paper-1617]
at com.github.games647.lagmonitor.traffic.TinyProtocol$1$1.channelRead(TinyProtocol.java:79) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) ~[patched_1.12.2.jar:git-Paper-1617]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.12.2.jar:git-Paper-1617]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
[19:50:46 ERROR]: Parameters:
net.minecraft.server.v1_12_R1.PacketPlayInSettings@696444fb[
a=en_us
b=16
c=FULL
d=true
e=127
f=Right
]`

I am using the latest (4.4.0) protocollib.
