### ISSUE TITLE
Tab-Complete java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by B4TT3RY** [Kugge/BestViewDistance#3]
**Describe the bug**
Tab Complete Exception

**To Reproduce**
*1. Type '/view ping''*
*2. See Error*
![image](https://user-images.githubusercontent.com/12368101/48334521-4adcb680-e69e-11e8-8f98-219172689e4d.png)

**Version**
Plugin: 6.1
Server: git-Paper-440 & git-Paper-441

**Error Log**
```
[17:09:36] [Netty Server IO #2/ERROR]: Exception when B4TT3RY__ attempted to tab complete view ping
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/view ping' in plugin BestViewDistance v6.1
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:144) ~[patched_1.13.2.jar:git-Paper-440]
	at org.bukkit.command.Command.tabComplete(Command.java:91) ~[patched_1.13.2.jar:git-Paper-440]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:227) ~[patched_1.13.2.jar:git-Paper-440]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabCompleteCommand(CraftServer.java:1772) ~[patched_1.13.2.jar:git-Paper-440]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.tabComplete(CraftServer.java:1744) ~[patched_1.13.2.jar:git-Paper-440]
	at org.bukkit.craftbukkit.v1_13_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[patched_1.13.2.jar:git-Paper-440]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:68) ~[patched_1.13.2.jar:git-Paper-440]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:379) ~[patched_1.13.2.jar:git-Paper-440]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:547) ~[patched_1.13.2.jar:git-Paper-440]
	at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:36) ~[patched_1.13.2.jar:git-Paper-440]
	at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-440]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:147) ~[patched_1.13.2.jar:git-Paper-440]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:136) ~[patched_1.13.2.jar:git-Paper-440]
	at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:358) ~[patched_1.13.2.jar:git-Paper-440]
	at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:31) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-440]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[patched_1.13.2.jar:git-Paper-440]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.13.2.jar:git-Paper-440]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at me.lxct.bestviewdistance.event.OnTabComplete.onTabComplete(OnTabComplete.java:26) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:132) ~[patched_1.13.2.jar:git-Paper-440]
	... 64 more
```

**Comment by Lxct** [comment]
I'll fix that in the next update. (6.4 is the current version).
Thanks for your report!

**Comment by Lxct** [comment]
Should be fixed in the latest update.
