### ISSUE TITLE
1.14.1 console eror

### ISSUE THREAD

**Issue by successed** [Kugge/BestViewDistance#31]
[18:03:22 WARN]: [BestViewDistance] Plugin BestViewDistance v11.9 generated an exception while executing task 4370
org.apache.commons.lang.NotImplementedException: Per-Player View Distance APIs need further understanding to properly implement
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.getViewDistance(CraftPlayer.java:1968) ~[patched_1.14.1.jar:git-Paper-42]
        at me.lxct.bestviewdistance.functions.Other.applyViewDistance(Other.java:83) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.1.jar:git-Paper-42]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.1.jar:git-Paper-42]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.1.jar:git-Paper-42]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by successed** [comment]
[18:16:57 ERROR]: Could not pass event PlayerJoinEvent to BestViewDistance v11.9
org.apache.commons.lang.NotImplementedException: Per-Player View Distance APIs need further understanding to properly implement
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.setViewDistance(CraftPlayer.java:1973) ~[patched_1.14.1.jar:git-Paper-42]
        at me.lxct.bestviewdistance.event.OnJoin.onPlayerJoin(OnJoin.java:21) ~[?:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.14.1.jar:git-Paper-42]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-42]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-42]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:169) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.1.jar:git-Paper-42]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.1.jar:git-Paper-42]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Redstone-ray** [comment]
Can confirm, BestViewDistance is broke in 1.14+

**Comment by HauserGrim** [comment]
https://github.com/graywolf336/BestViewDistance/issues/10#issuecomment-496537467

**Comment by sofianedjerbi** [comment]
Duplicate.
