### ISSUE TITLE
BestViewDistance v12 generated an exception while executing task 27

### ISSUE THREAD

**Issue by Weasel-Beans** [Kugge/BestViewDistance#33]
**Describe the bug**
A message that appears in my console every few seconds.

**To Reproduce**
Turn on the server and look at the console.

**Expected behavior**
Nothing

**Timings**
https://timings.aikar.co/?id=afa0f97a84084338a6cb0ba3bd33c6d9

**Additional context**
[19:17:15 WARN]: [BestViewDistance] Plugin BestViewDistance v12 generated an exception while executing task 27
org.apache.commons.lang.NotImplementedException: Per-Player View Distance APIs need further understanding to properly implement
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.getViewDistance(CraftPlayer.java:1989) ~[patched_1.14.3.jar:git-Paper-121]
at me.lxct.bestviewdistance.functions.BVDPlayer.getCurrentViewDistance(BVDPlayer.java:156) ~[?:?]
at me.lxct.bestviewdistance.functions.util.Calculations.applyViewDistance(Calculations.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-121]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.3.jar:git-Paper-121]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.3.jar:git-Paper-121]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by sofianedjerbi** [comment]
Please read issue #32
